# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 228b12333a4b4c5b08ad2912dcd70a4d0b8a7f6debe0ee914fba50ed9085e35bab29a89e75f7d794f3498f96b6e63c4d816214744b059a791d92f3b8a46d4ff3

test:
  secret_key_base: eb663f4c3b9b842467daa6abe2304e5b5fe355b1edcb3117254ed02a8b0ee5a0fb1c76b49645fb8ee5b1415d8198eab2f168f56ff5185a00917b208b2a13cdcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
